
---
#title: "What, Why, and How -- Generative AI Blogs"
author: Xiaoqing Chen
theme: minima
date: 
description: What I cannot prove, I don't understand. 
---


  
# social links
social-network-links:
  twitter: Skylar13Chen # DO NOT include the @ character, or else the build will fail!
  github: xc308 # DO NOT include the @ character, or else the build will fail!
  
show_excerpts:true # set to false to remove excerpts on the homepage
  
share-links-active:
  twitter: true
  github: true
  

  
